name: chat
channels:
  - defaults
dependencies:
  - pip:
      - playwright
      - python-dotenv
      - python-telegram-bot==20.0a6
      - python-telegram-bot[job-queue]
      - requests
      - google-search-results
      - git+https://github.com/python-telegram-bot/ptbcontrib.git@main
      - -r requirements.txt
